# 1. input
input{
    file {
        # 도커 컨테이너 안에서 바라보는 우리 로그 파일의 위치
        path => '/usr/share/logstash/logs/waiting-api-log.log'

        # 처음 켤 때 싹다 읽어오라는 뜻
        start_position => "beginning"

        # 연습 중에는 Logstash 재시작 때 같은 파일을 다시 읽는다. 운영에서는 중복 적재를 피하려고 sincedb를 유지해야 한다.
        sincedb_path => "/dev/null"

        # 파일 변경 확인 주기
        stat_interval => "1 second"
    }
}

# 2 filter
filter{
    grok {
        match => {
            "message" => "^(?<log_time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\s+%{LOGLEVEL:level}\s+\[(?<traceId>[^\]]*)\]\s+%{DATA:logger}\s+:\s+%{GREEDYDATA:log_message}$"
        }
        tag_on_failure => ["_arcane_grok_failure"]
    }

    date {
        match => ["log_time", "yyyy-MM-dd HH:mm:ss"]
        target => "@timestamp"
        timezone => "Asia/Seoul"
    }

}

# 3 output
output{
    # 목적지인 엘라스틱 서치로 보냄
    elasticsearch{
        hosts=> ["http://elasticsearch:9200"]
        # 저장될 인덱스 이름
        index => "waiting-api-logs-%{+YYYY.MM.dd}"
    }
    stdout {codec => rubydebug}
}
