apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    editable: true
    jsonData:
      index: arcane-logs-*
      timeField: "@timestamp"
      interval: Daily
